---
abstract: 'A generalised API version of David Golden''s visitcpan'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.86
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: CPAN::Mini::Visit
name: CPAN-Mini-Visit
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/CPAN-Mini-Visit
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/CPAN-Mini-Visit
version: 0.01
